cleaners/urls.py
from django.conf.urls import url
from . import views

# Namespace to differentiate among apps
app_name = 'cleaners'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about$', views.about, name='about'),
    url(r'^services$', views.services, name='services'),
    url(r'^pick-up$', views.pick_up, name='pick_up'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^thank-you', views.thank_you, name='thank_you'),
    url(r'^one_page$', views.one_page, name='one_page'),  # TODO-me: To be removed?
]

drycleaners/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('cleaners.urls')),
    url(r'^admin/', admin.site.urls),
]

cleaners/models.py
from django.db import models

# Create your models here.

cleaners/forms.py
from django import forms

from django.core.validators import EmailValidator
from django.core.validators import ValidationError
from django.utils.translation import ugettext_lazy as _

# Possible types of carpet
CARPET_TYPE = (
    ('', 'Select a carpet type'),
    ('NRM', 'Normal'),
    ('SLK', 'Silk'),
    ('WOL', 'Wool'),
    ('PER', 'Persian')
)


class CalculationForm(forms.Form):
    carpet_types = forms.ChoiceField(initial='', choices=CARPET_TYPE, label='Carpet Types',)

    length = forms.FloatField(min_value=0)

    width = forms.FloatField(min_value=0)


class ContactForm(forms.Form):
    subject = forms.CharField(label='Subject',
                              required=True)

    email_from = forms.EmailField(label='E-mail address', required=True,
                                  max_length=100,
                                  error_messages={'invalid': 'Please enter a valid email address (e.g. joesmith@abc.com)'},
                                  )  # TODO-me: Change the email address example

    message = forms.CharField(label='Message',
                              required=True)

    # Validate email
    def clean_email_from(self):  # TODO-me: Write tests for this
        email = self.cleaned_data['email_from']
        validator = EmailValidator()
        try:
            validator(email)
        except ValidationError:
            raise ValidationError(_('Your email address is invalid. Please enter a correct one'))

        return email


class PickupForm(forms.Form):  # TODO-me: Used to render the pickup form in the pickup/delivery page
    name = forms.CharField(label='Name', required=True)

    customer_email = forms.EmailField(label='E-mail address', required=True,
                                      max_length=100,
                                      error_messages={'invalid': 'Please enter a valid email address (e.g. joesmith@abc.com)'},
                                      )  # TODO-me: Change the email address example

cleaners/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import CalculationForm, ContactForm


def index(request):

    if request.method == 'GET':
        calculation_form = CalculationForm()
    # else:
    #     calculation_form = CalculationForm(request.POST)  # TODO-me: Is this POST handling needed?
    #
    #     if calculation_form.is_valid():
    #         carpet_types = calculation_form.cleaned_data['carpet_types']
    #         length = calculation_form.cleaned_data['length']
    #         width = calculation_form.cleaned_data['width']
    #
    #         return HttpResponseRedirect(reverse('cleaners:services'))

    return render(request, 'index.html', {'form': calculation_form})


def about(request):
    return render(request, 'about.html')


def services(request):
    return render(request, 'services.html')


def pick_up(request):
    # If this is a GET request create the calculation form
    if request.method == 'GET':
        calculation_form_pickup = CalculationForm()
    else:
        calculation_form_pickup = CalculationForm(request.POST)

        if calculation_form_pickup.is_valid():
            carpet_type = calculation_form_pickup.cleaned_data['carpet_types']
            length = calculation_form_pickup.cleaned_data['length']
            width = calculation_form_pickup.cleaned_data['width']
            service_cost = request.POST.get('service_cost')

            return render(request, 'pickup_delivery.html', {'service_cost': service_cost, 'carpet_type': carpet_type,
                                                            'length': length, 'width': width})

    return render(request, 'pickup_delivery.html', {'form': calculation_form_pickup})


def thank_you(request):
    return render(request, 'thank-you.html')


# Using function-based view instead of the generic class based FormView in order to have
# better control of the form processing
def contact(request):
    # If this is a GET request create the contact form
    if request.method == 'GET':
        contact_form = ContactForm()
    # If this is a POST request then process the data
    else:
        # Create a form instance and bind the data request to it
        contact_form = ContactForm(request.POST)

        # Check if the form is valid and process its data
        if contact_form.is_valid():
            subject = contact_form.cleaned_data['subject']
            email_from = contact_form.cleaned_data['email_from']
            message = contact_form.cleaned_data['message']

            try:
                send_mail(subject, message, email_from, ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')

            return HttpResponseRedirect(reverse('cleaners:thank_you'))

    return render(request, 'contact.html', {'form': contact_form})


def one_page(request):
    return render(request, 'onepage.html')

cleaners/templates/about.html
{% extends "base_generic.html" %}

{% load static %}

{% block title %}
    <title>About Us</title>
{% endblock%}

{% block homeSection %}
        <section class="probootstrap_section" id="section-feature-testimonial">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-12 text-center mb-5 probootstrap-animate about-page">
            <h2 class="display-4 border-bottom probootstrap-section-heading">Why we Love Places</h2>
            <blockquote class="">
              <p class="lead mb-4"><em>About us text will go here. And it will look like this and like this and like this.
                                       To be populated with more info. So more details about the business have to go
              here. So this won't look so empty. At least four or five more sentences will go here in order to fill that
              void. But we have to be careful as to what we will put here.</em></p>
              <p class="probootstrap-author">
                <a href={% static 'assets/images/person_1.jpg' %}" target="_blank">
                  <img src="{% static 'assets/images/person_1.jpg' %}" alt="founder-face" class="rounded-circle">
                  <span class="probootstrap-name">Aristides Papanikolaou</span>
                  <span class="probootstrap-title">Founder</span>
                </a>
              </p>
            </blockquote>

          </div>
        </div>

      </div>
    </section>
    <!-- END section -->
{% endblock %}

{% block content %}
    <!-- Main content to be inserted here-->
{% endblock %}

cleaners/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
	<head>
      <!--
    IMPORTANT: You can do whatever you want with this template but you need to keep the footer link back to ProBootstrap.com
    -->

    {% block title %}<title>Dream Clean </title>{% endblock%}
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="The best carpet pickup and delivery dry-cleaning service in Athens. Calculate online
	    the price you'll be paying."> <!--TODO-me: FINALIZE THE DESCRIPTION -->

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">

    <!-- Load the css files -->

    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons/css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">

    <link rel="stylesheet" href="{% static 'assets/fonts/flaticon/font/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'assets/fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/select2.css' %}">


    <link rel="stylesheet" href="{% static 'assets/css/helpers.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

	</head>

	<body>

    <!-- START nav -->
    <nav class="navbar navbar-expand-lg navbar-dark probootstrap_navbar" id="probootstrap-navbar">
      <div class="container">
        <a class="navbar-brand" href="{% url 'cleaners:index' %}">Dream Clean</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-menu" aria-controls="probootstrap-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span><i class="ion-navicon"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="probootstrap-menu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url 'cleaners:about' %}">Who we are</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'cleaners:services' %}">Services</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'cleaners:pick_up' %}">Pick Up/Delivery</a></li>
{#            <li class="nav-item"><a class="nav-link" href="travel.html">Location</a></li>  TODO-me: Do we need this?#}
            <li class="nav-item"><a class="nav-link" href="{% url 'cleaners:contact' %}">Contact</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- END nav -->

    <!-- START Home section -->
    <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url({% static 'assets/images/img_main.jpg' %});" data-stellar-background-ratio="0.5"  id="section-home">
      <div class="overlay"></div>
        {% block homeSection %}{% endblock %}
    </section>
    <!-- END Home Section -->

    {% block content %}{% endblock %}

      <footer id="footer">
        <div class="row mb-5">
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="https://free-template.co" target="_blank">Home</a></li>
              <li><a href="https://free-template.co" target="_blank">About</a></li>
              <li><a href="https://free-template.co" target="_blank">Services</a></li>
              <li><a href="https://free-template.co" target="_blank">Contact</a></li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="https://free-template.co" target="_blank">Home</a></li>
              <li><a href="https://free-template.co" target="_blank">About</a></li>
              <li><a href="https://free-template.co" target="_blank">Services</a></li>
              <li><a href="https://free-template.co" target="_blank">Contact</a></li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="https://free-template.co" target="_blank">Home</a></li>
              <li><a href="https://free-template.co" target="_blank">About</a></li>
              <li><a href="https://free-template.co" target="_blank">Services</a></li>
              <li><a href="https://free-template.co" target="_blank">Contact</a></li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="https://free-template.co" target="_blank">Home</a></li>
              <li><a href="https://free-template.co" target="_blank">About</a></li>
              <li><a href="https://free-template.co" target="_blank">Services</a></li>
              <li><a href="https://free-template.co" target="_blank">Contact</a></li>
            </ul>
          </div>
        </div>
        <div class="row pt-5">
          <div class="col-md-12 text-center">
            <p class="probootstrap_font-14">&copy; 2018. All Rights Reserved. <br> Designed &amp; Developed by <a href="https://probootstrap.com/" target="_blank">ProBootstrap</a><small> (Don't remove credit link on this footer. See <a href="https://probootstrap.com/license/">license</a>)</small></p>
            <p class="probootstrap_font-14">Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
          </div>
        </div>
      </footer>

    {% block js %}

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>

    <script src="{% static 'assets/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>

    <script src="{% static 'assets/js/select2.min.js' %}"></script>

    <script src="{% static 'assets/js/main.js' %}"></script>

    {% endblock %}

	</body>
</html>

cleaners/templates/city-guides.html
<!DOCTYPE html>
<html lang="en">
	<head>
      <!-- 
    More Templates Visit ==> ProBootstrap.com
    Free Template by ProBootstrap.com under the License Creative Commons 3.0 ==> (probootstrap.com/license)

    IMPORTANT: You can do whatever you want with this template but you need to keep the footer link back to ProBootstrap.com
    -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<title>Places &mdash; Free HTML5 Bootstrap 4 Theme by ProBootstrap.com</title>
		<meta name="description" content="Free Bootstrap 4 Theme by ProBootstrap.com">
		<meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">

		<link rel="stylesheet" href="assets/css/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="assets/css/animate.css">
    <link rel="stylesheet" href="assets/fonts/ionicons/css/ionicons.min.css">
    
    <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
    
    <link rel="stylesheet" href="assets/fonts/flaticon/font/flaticon.css">

    <link rel="stylesheet" href="assets/fonts/fontawesome/css/font-awesome.min.css">

    <link rel="stylesheet" href="assets/css/select2.css">
    

    <link rel="stylesheet" href="assets/css/helpers.css">
    <link rel="stylesheet" href="assets/css/style.css">

	</head>
	<body>
  

    <nav class="navbar navbar-expand-lg navbar-dark probootstrap_navbar" id="probootstrap-navbar">
      <div class="container">
        <a class="navbar-brand" href="/">Places</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#probootstrap-menu" aria-controls="probootstrap-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span><i class="ion-navicon"></i></span>
        </button>
        <div class="collapse navbar-collapse" id="probootstrap-menu">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="index.html">Home</a></li>
            <li class="nav-item active"><a class="nav-link" href="city-guides.html">City Guides</a></li>
            <li class="nav-item"><a class="nav-link" href="services.html">Services</a></li>
{#            <li class="nav-item"><a class="nav-link" href="travel.html">Travel With Us</a></li>#}
            <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- END nav -->
    

    <section class="probootstrap-cover overflow-hidden relative"  style="background-image: url('assets/images/bg_1.jpg');" data-stellar-background-ratio="0.5" id="section-home">
      <div class="overlay"></div>
      <div class="container">
        <div class="row align-items-center text-center">
          <div class="col-md">
            <h2 class="heading mb-2 display-4 font-light probootstrap-animate">City Guides</h2>
             
            <p class="lead mb-5 probootstrap-animate">
              

            </p>
              <a href="https://themewagon.com/theme_tag/free/" target="_blank" role="button" class="btn btn-primary p-3 mr-3 pl-5 pr-5 text-uppercase d-lg-inline d-md-inline d-sm-block d-block mb-3">More Templates Here</a> 
            </p>
          </div> 
        </div>
      </div>
    
    </section>
    <!-- END section -->
    
    <section class="probootstrap_section" id="section-city-guides">
      <div class="container">
        <div class="row text-center mb-5 probootstrap-animate">
          <div class="col-md-12">
            <h2 class="display-4 border-bottom probootstrap-section-heading">Top Places Around The World</h2>
          </div>
        </div>
        <div class="row mb-4">
          <div class="col-lg-3 col-md-6 probootstrap-animate mb-3">
            <a href="#" class="probootstrap-thumbnail">
              <img src="assets/images/img_1.jpg" alt="Free Template by ProBootstrap.com" class="img-fluid">
              <div class="probootstrap-text">
                <h3>Buena</h3>
              </div>
            </a>
          </div>
          <div class="col-lg-3 col-md-6 probootstrap-animate mb-3">
            <a href="#" class="probootstrap-thumbnail">
              <img src="assets/images/img_2.jpg" alt="Free Template by ProBootstrap.com" class="img-fluid">
              <h3>Road</h3>
            </a>
          </div>
          <div class="col-lg-3 col-md-6 probootstrap-animate mb-3">
            <a href="#" class="probootstrap-thumbnail">
              <img src="assets/images/img_3.jpg" alt="Free Template by ProBootstrap.com" class="img-fluid">
              <h3>Australia</h3>
            </a>
          </div>
          <div class="col-lg-3 col-md-6 probootstrap-animate mb-3">
            <a href="#" class="probootstrap-thumbnail">
              <img src="assets/images/img_4.jpg" alt="Free Template by ProBootstrap.com" class="img-fluid">
              <h3>Japan</h3>
            </a>
          </div>
        </div>


        <div class="row">
          <div class="col-lg-3 col-md-6 probootstrap-animate mb-3">
            <a href="#" class="probootstrap-thumbnail">
              <img src="assets/images/img_5.jpg" alt="Free Template by ProBootstrap.com" class="img-fluid">
              <div class="probootstrap-text">
                <h3>Paris</h3>
              </div>
            </a>
          </div>
          <div class="col-lg-3 col-md-6 probootstrap-animate mb-3">
            <a href="#" class="probootstrap-thumbnail">
              <img src="assets/images/img_2.jpg" alt="Free Template by ProBootstrap.com" class="img-fluid">
              <h3>Brazil</h3>
            </a>
          </div>
          <div class="col-lg-3 col-md-6 probootstrap-animate mb-3">
            <a href="#" class="probootstrap-thumbnail">
              <img src="assets/images/img_3.jpg" alt="Free Template by ProBootstrap.com" class="img-fluid">
              <h3>Australia</h3>
            </a>
          </div>
          <div class="col-lg-3 col-md-6 probootstrap-animate mb-3">
            <a href="#" class="probootstrap-thumbnail">
              <img src="assets/images/img_4.jpg" alt="Free Template by ProBootstrap.com" class="img-fluid">
              <h3>Japan</h3>
            </a>
          </div>
        </div>

        <div class="row justify-content-center probootstrap-animate">
          <div class="col-md-3"><a href="https://themewagon.com/theme_tag/free/" target="_blank" class="btn btn-primary">More Templates Here</a></div>
        </div>

      </div>
    </section>

    <section class="probootstrap_section" id="section-feature-testimonial">
      <div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-12 text-center mb-5 probootstrap-animate">
            <h2 class="display-4 border-bottom probootstrap-section-heading">Why we Love Places</h2>
            <blockquote class="">
              <p class="lead mb-4"><em>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</em></p>
              <p class="probootstrap-author">
                <a href="https://probootstrap.com/" target="_blank">
                  <img src="assets/images/person_1.jpg" alt="Free Template by ProBootstrap.com" class="rounded-circle">
                  <span class="probootstrap-name">James Smith</span>
                  <span class="probootstrap-title">Chief Executive Officer</span>
                </a>
              </p>
            </blockquote>

          </div>
        </div>
        
      </div>
    </section>
    <!-- END section -->

    <footer class="probootstrap_section probootstrap-border-top">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="https://free-template.co" target="_blank">Home</a></li>
              <li><a href="https://free-template.co" target="_blank">About</a></li>
              <li><a href="https://free-template.co" target="_blank">Services</a></li>
              <li><a href="https://free-template.co" target="_blank">Contact</a></li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="https://free-template.co" target="_blank">Home</a></li>
              <li><a href="https://free-template.co" target="_blank">About</a></li>
              <li><a href="https://free-template.co" target="_blank">Services</a></li>
              <li><a href="https://free-template.co" target="_blank">Contact</a></li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="https://free-template.co" target="_blank">Home</a></li>
              <li><a href="https://free-template.co" target="_blank">About</a></li>
              <li><a href="https://free-template.co" target="_blank">Services</a></li>
              <li><a href="https://free-template.co" target="_blank">Contact</a></li>
            </ul>
          </div>
          <div class="col-md-3">
            <h3 class="probootstrap_font-18 mb-3">Quick Links</h3>
            <ul class="list-unstyled">
              <li><a href="https://free-template.co" target="_blank">Home</a></li>
              <li><a href="https://free-template.co" target="_blank">About</a></li>
              <li><a href="https://free-template.co" target="_blank">Services</a></li>
              <li><a href="https://free-template.co" target="_blank">Contact</a></li>
            </ul>
          </div>
        </div>
        <div class="row pt-5">
          <div class="col-md-12 text-center">
            <p class="probootstrap_font-14">&copy; 2017. All Rights Reserved. <br> Designed &amp; Developed by <a href="https://probootstrap.com/" target="_blank">ProBootstrap</a><small> (Don't remove credit link on this footer. See <a href="https://probootstrap.com/license/">license</a>)</small></p>
            <p class="probootstrap_font-14">Demo Images: <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
          </div>
        </div>
      </div>
    </footer>

    
    <script src="assets/js/jquery.min.js"></script>
    
    <script src="assets/js/popper.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/owl.carousel.min.js"></script>
    
    <script src="assets/js/jquery.waypoints.min.js"></script>
    <script src="assets/js/jquery.easing.1.3.js"></script>

    <script src="assets/js/select2.min.js"></script>

    <script src="assets/js/main.js"></script>
	</body>
</html>

cleaners/templates/contact.html
{% extends "base_generic.html" %}

{% load static %}

{% block title %}
    <title>Contact Information</title>
{% endblock%}

{% block homeSection %}
    <!-- Section to be inserted here -->
{% endblock %}

{% block content %}

    <div class="jumbotron jumbotron-sm">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-lg-12">
                    <h1 class="h1">
                        Get in touch!
                    </h1>
                </div>
            </div>
        </div>
    </div>
    <!-- END Contact header -->

    {% if form.errors %}
        <div>
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger" id ="form-errors">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        </div>
    {% endif %}
    <!-- END Form errors section -->

    <div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST" class="post-form">
            {% csrf_token %}

                    <div class="well well-sm">
                        <div class="row form-line">
                            <div class="col-md-6">

                                <div class="form-group">
                                    <label for="{{ form.subject.id_for_label }}">{{ form.subject.label_tag }}</label>
                                     <input type="text" name="{{ form.subject.html_name }}" class="form-control"
                                            id="subject" placeholder='Enter your subject'>
                                </div>
                                <!-- END subject section -->

                                <div class="form-group">
                                    <label for="{{ form.email_from.id_for_label }}">{{ form.email_from.label_tag }}</label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                        </span>
                                        <input type="email" name="{{ form.email_from.html_name }}" class="form-control"
                                               id="inputEmail" placeholder='Enter your email'>
                                    </div>
                                </div>
                                <!-- END email section -->
                            </div>
                            <!-- END left column -->

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for ="{{ form.message.id_for_label }}"> {{ form.message.label_tag }}</label>
                                     <textarea type="text" class="form-control" rows='5' cols='5'
                                               name="{{ form.message.html_name }}" id="description"
                                               placeholder="Type your message">

                                     </textarea>
                                </div>
                            </div>

                            <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary float-md-right" id="btnContactUs">
                                        Send</button>
                            </div>
                            </div>
                            <!-- END message section -->

                        </div>
            </form>
        </div>
        <div class="col-md-4" id="contact_col">
            <legend><span class="glyphicon glyphicon-globe"></span> Our office</legend>
            <address>
                <strong>Papanikolaou</strong><br>
                Neos kosmos<br>
                Athina<br>
                <abbr title="Phone">
                    Tel:</abbr>
                210-4455889
            </address>
        </div>
    </div>

    </div>

{% endblock %}

cleaners/templates/main_calculation_form.html
<form action="{% url 'cleaners:pick_up' %}"  method="POST" id="main_form" class="probootstrap-form">
{% csrf_token %}
<div class="form-group">
<div class="row">
  <div class="col-md">
    <div class="probootstrap-size-wrap">
      <label for="{{ form.carpet_types.id_for_label }}">{{ form.carpet_types.label_tag }}</label>

      <!-- <label for="id_label_single" style="width: 100%;"> -->
        <select class="js-example-basic-single js-states form-control" id="id_label_single" name="carpet_types"
                style="width: 100%;">
            {% for choice in form.carpet_types.field.choices %}
                <option value="{{choice.0}}" name="{{form.carpet_types.html_name}}">{{choice.1}}</option>
            {% endfor %}
        </select>
      <!-- </label> -->

     </div>
  </div>
</div>
  <!-- END carpet type row -->

<div class="row carpet-length">
  <div class="col-md meters-column">
    <div class="form-group" id="calc_main">
      <label for="{{ form.length.id_for_label }}">{{ form.length.label_tag }}</label>
      <div class="probootstrap-size-wrap">
        <input type="text" id="length" class="form-control" name="{{ form.length.html_name }}"
               placeholder="Enter the length of your carpet">
      </div>
    </div>
  </div>
</div>
<!-- END length row -->

<div class="row carpet-width">
  <div class="col-md meters-column">
    <div class="form-group" id="calc_main">
      <label for="{{ form.width.id_for_label }}">{{ form.width.label_tag }}</label>
      <div class="probootstrap-size-wrap">
        <input type="text" id="width" class="form-control" name="{{ form.width.html_name }}"
               placeholder="Enter the width of your carpet">
      </div>
    </div>
  </div>
</div>
<!-- END width row -->

<input type="hidden" id="service_cost" name="service_cost" value="">

<div class="row">
  <div class="col-sm-12 calculate">
    <input type="submit" id="calculate_btn" value="Calculate" class="btn btn-primary btn-block">
  </div>
</div>
</div>
</form> <!-- END form -->